title: "myamyu's github page"
email: "myamyu@gmail.com"
description: "myamyuのGithub Page"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://myamyu.github.io" # the base hostname & protocol for your site
author:
  twitter: myamyu
  github: myamyu
twitter:
  username: myamyu
github:
  username:  myamyu
timezone: Asia/Tokyo
markdown: kramdown
collections:
  posts:
    permalink: /posts/:categories/:year-:month-:day/:title/
paginate: 5
paginate_path: "posts/page:num"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
