title: "myamyu's github page"
email: "myamyu@gmail.com"
description: "myamyu's github page"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://myamyu.github.io" # the base hostname & protocol for your site
author:
  twitter: myamyu
  github: myamyu
twitter:
  username: myamyu
github:
  username:  myamyu
timezone: Asia/Tokyo
markdown: kramdown
kramdown:
  input: GFM
future: false
exclude: [vendor]
collections:
  posts:
    permalink: /posts/:categories/:year-:month-:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "page_en"
paginate: 5
paginate_path: "posts/page:num"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
