version: 2
jobs:
  setup: &exector
    working_directory: ~/work
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/work/node_modules
      - persist_to_workspace: &save_workspace
          root: .
          paths:
            - ./*
  build:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run vuepress build
          command: npm run build:doc
      - persist_to_workspace:
          <<: *save_workspace
  deploy:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "93:07:ed:ba:de:ed:09:8a:27:e0:3d:35:3a:7c:91:4c"
      - run:
          name: Deploy to Github Pages.
          command: npm run deploy
workflows:
  version: 2
  deploy_to_hosting:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - setup
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
