version: 2
jobs:
  setup: &exector
    working_directory: ~/work
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/work/node_modules
      - persist_to_workspace: &save_workspace
          root: .
          paths:
            - ./*
  build:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run vuepress build
          command: npm run build:doc
      - persist_to_workspace:
          <<: *save_workspace
  deploy:
    <<: *exector
    environment:
      PAGES_WORK: ~/pages_work
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "93:07:ed:ba:de:ed:09:8a:27:e0:3d:35:3a:7c:91:4c"
      - run:
          name: clone page resources.
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone -b gh-pages git@github.com:myamyu/myamyu.github.io.git ${PAGES_WORK}
      - run:
          name: copy docs
          command: cp -ap .vuepress/dist/. $PAGES_WORK
      - run: git --work-tree ${PAGES_WORK} status
      - run: 
          name: deploy to github pages
          command: |
            git config user.email "circleci+myamyu@users.noreply.github.com"
            git config user.name "CircleCI"
            git --work-tree ${PAGES_WORK} add --all
            git --work-tree ${PAGES_WORK} commit -m "[skip ci] deploy to gh-pages from `git rev-parse --short HEAD`"
            git --work-tree ${PAGES_WORK} push
workflows:
  version: 2
  deploy_to_hosting:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - setup
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
