title: About みゃみゅ玉子（Myamyu-Tamago）
description: みゃみゅ玉子（Myamyu-Tamago）による自己紹介サイトです。
head:
  - 
    - link
    - 
      rel: icon
      href: /favicon.ico
locales:
  "/":
    lang: 'ja'
  "/en/":
    lang: 'en-US'
    title: About Myamyu-Tamago
    description: I am Myamyu.
